name: Jsonnet Updater
description: Update vendored jsonnet libraries
inputs:
  jsonnet-file:
    required: false
    default: ./jsonnetfile.json
  git-user-name:
    required: true
  git-user-email:
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    JSONNET_FILE: ${{ inputs.jsonnet-file }}
    GIT_USER_NAME: ${{ inputs.git-user-name }}
    GIT_USER_EMAIL: ${{ inputs.git-user-email }}
