name: Jsonnet Updater
on:
  # For testing.
  workflow_dispatch:

jobs:
  Jsonnet-Updater:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run Jsonnet Updater
      uses: tomwilkie/jsonnet-updater@v0.3
      args:
        git-user-name: Tom Wilkie
        git-user-email: tom.wilkie@gmail.com
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
